### ISSUE TITLE
Rename https://github.com/finos/cfi-terraform-gcp-ocp

### ISSUE THREAD

**Issue by AdrianHammond** [finos/ansible-cfi-ocp#1]
Hi @mcleo-d  - to progress finos/compliant-financial-infrastructure#253 we need a repo to store our Ansible playbooks, our intent is for the playbooks to be cloud provider agnostic. Would it be possible to rename https://github.com/finos/cfi-terraform-gcp-ocp this repo to cfi-ansible-ocp or delete it and create a new repo for us to use.  Thanks A

**Comment by eddie-knight** [comment]
Transferring this issue to the repo in question just for the visibility over there. 

@AdrianHammond would it be more fitting to name it `ansible-gcp-cfi-ocp` to match the format we landed on with [terraform-aws-cfi-eks](https://github.com/finos/terraform-aws-cfi-eks)?

We should ping Juan request help actioning once a name is confirmed.

**Comment by AdrianHammond** [comment]
Thanks @eddie-knight our plan is to control the cloud provider through variables so we should need just a single repo, rather than a separate repo per cloud provider e.g. ansible-gcp-cfi-ocp, ansible-aws-cfi-ocp, ansible-azure-cfi-ocp etc. 

So could we go with ansible-cfi-ocp ?

**Comment by eddie-knight** [comment]
Brialliant.

@TheJuanAndOnly99 could you please help us action this?

**Comment by TheJuanAndOnly99** [comment]
@eddie-knight @AdrianHammond I've renamed the repo. Please verify and feel free to close the issue. Thanks!

**Comment by eddie-knight** [comment]
Thanks @TheJuanAndOnly99 !
