### ISSUE TITLE
Move implementation documentation and code examples from CFI repo to ansible-cfi-ocp

### ISSUE THREAD

**Issue by AdrianHammond** [finos/ansible-cfi-ocp#4]
Move documentation and code examples that were created to support OCP on GCP from https://github.com/finos/compliant-financial-infrastructure/tree/dev/accelerators/kubernetes/ocp/gcp to https://github.com/finos/ansible-cfi-ocp

**Comment by AdrianHammond** [comment]
Two pull request created and ready for review. 

1. move OCP doc from main CFI repo to ansible-cfi-ocp #5 
2. remove OCP on GCP doc from main https://github.com/finos/compliant-financial-infrastructure/pull/307

**Comment by AdrianHammond** [comment]
Opened up https://github.com/finos/compliant-financial-infrastructure/discussions/new?category=general to agree path to progress this issue.

**Comment by abassettRH** [comment]
Issue completed - merged into dev with PR#15

**Comment by AdrianHammond** [comment]
closing as merged into dev
